version: "2"
services:

  doctorservice:
    build: ./
    network_mode: host
    ports:
      - 8082:8082
    expose:
      - 8082

  mongo:
    image: mongo:3.4-xenial
    restart: always
    network_mode: host
    volumes:
      ['/home/shahina/data:/data/db']
    ports:
      - 27017:27017
    expose:
      - 27017